name: Claude Code (Self-hosted)
on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  claude-code:
    if: contains(github.event.comment.body, '@claude')
    runs-on: self-hosted  # セルフホストrunnerを使用
    steps:
      - uses: actions/checkout@v4
      - name: Run Claude with prompt flag
        run: |
          echo "${{ github.event.comment.body }}" | claude -p "GitHub issue comment from ${{ github.event.comment.user.login }}: "
